server:
  port: 8080

paths:
  career-service: http://localhost:8081
  career-ai-service: http://localhost:8082

spring:
  application:
    name: CRR-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: career-service
              uri: ${paths.career-service}
              predicates:
                - Path=/api/v1/pdf/**, /api/v1/scrapper/**

            - id: career-ai-service
              uri: ${paths.career-ai-service}
              predicates:
                - Path=/api/v1/cv/**, /api/v1/offer/**

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: "Career Service"
        url: "${paths.career-service}/api/openapi.yaml"
      - name: "Career AI Service"
        url: "${paths.career-ai-service}/openapi.json"